# Generated by Django 4.2.13 on 2024-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(default='Egyptian', max_length=100),
        ),
    ]
