# Generated by Django 4.2.13 on 2024-06-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_registeruser_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='password1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='password2',
            field=models.CharField(max_length=60),
        ),
    ]
