# Generated by Django 4.2.13 on 2024-06-28 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myApp.registeruser'),
        ),
    ]
