# Generated by Django 4.2.13 on 2024-06-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_customuser_alter_login_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
