# Generated by Django 4.2.13 on 2024-06-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_userprofile_picture_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speciallization',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
